name: Java CI with contracts run through command line

on:
  push:
    branches: [ github-actions-setup-specmatic ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run springboot application
      working-directory: main
      run: nohup mvn spring-boot:run &
    - name: Wait for springboot application to start
      run: sleep 30s
      shell: bash
    - name: Setup specmatic
      uses: airslate-oss/setup-specmatic@v1
      with:
        specmatic-version: 0.59.0
    - name: Run Specmatic contract as test
      run: ls -l && specmatic test --port 8080 --junitReportDir contract-test-reports
    - name: Publish contract test report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/contract-test-reports/TEST-*.xml'
